### ISSUE TITLE
Error while compiling watcher.lisp

### ISSUE THREAD

**Issue by whatacold** [sharplispers/log4cl#25]
Hi,

I try to quickload log4cl, but failed:

    COMPILE-FILE-ERROR while
    compiling #<CL-SOURCE-FILE "log4cl" "src" "watcher">
       [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]

And `*slime-repl sbcl*` buffer:

    ; file: /home/whatacold/quicklisp/dists/quicklisp/software/log4cl-20170124-git/src/watcher.lisp
    ; in: DEFUN START-HIERARCHY-WATCHER-THREAD
    ;     (LOG4CL-IMPL:LOG-DEBUG "Watcher thread already started")
    ; 
    ; caught ERROR:
    ;   during macroexpansion of (LOG-DEBUG "Watcher thread already started"). Use
    ;   *BREAK-ON-SIGNALS* to intercept.
    ;   
    ;    The value
    ;      "WITHOUT-INTERRUPTS-BODY-1"
    ;    is not of type
    ;      LIST

I use SBCL, is it a bug, or do I miss something?
Thank.

**Comment by whatacold** [comment]
I try ` (let ((*break-on-signals 'error)) (ql:quickload :log4cl))` in order to trap into the debugger to see what go wrong, but it succeed to install log4cl. As a Lisp beginner, I can't figure out why:(

**Comment by whatacold** [comment]
Close this as I can't reproduce it now :(

**Comment by imnisen** [comment]
I come with exactly the same error when install `log4cl` with quickload. While I don't have `cl-ppcre` installed locally.

 Environment:  SBCL 1.3.19, Mac os 10.13.4

**Comment by imnisen** [comment]
May be the version `log4cl-20170124`  quicklisp use has a bug? when I clone from github into `quicklisp/local-projects`, I can load it without error.
