### ISSUE TITLE
cleanup: use semaphores for bordeaux-threads

### ISSUE THREAD

**Issue by dkochmanski** [sharplispers/log4cl#26]
Previously BT didn't have semaphores implementation – it does now. Last year we've removed dependency on bt-semaphore in favour of hand-crafted CV-based solution. We should revert part of this pull request: https://github.com/sharplispers/log4cl/pull/18 and use semaphore interface from BT now (file `watcher.lisp`).

This task does not require deep understanding of log4cl internals whatsoever and may be solved by beginners to get involved into the project.

**Comment by chuchana** [comment]
I guess this can be closed now? (https://github.com/sharplispers/log4cl/pull/28)

**Comment by dkochmanski** [comment]
yes, thank you for bumping this thread. closing.
