### ISSUE TITLE
log4cl not working anymore with SBCL 1.4.16

### ISSUE THREAD

**Issue by MartinBuchmann** [sharplispers/log4cl#29]
I am using log4cl with SBCL 1.4.16 on macOS with Emacs 26.1 and get the following error when invoking slime 

`Can’t load log4slime lisp support: COMPILE-FILE-ERROR while compiling #<SWANK-LOADER-FILE "swank" "swank-loader">.`

I have no further information and do not know how to investigate this. I was using log4cl in the past without any issue. As far as I can tell the issue came up with the update to sbcl 1.4.16. Can anyone confirm this issue?

**Comment by scymtym** [comment]
Is there any additional output in the `*inferior-lisp*` buffer?

**Comment by MartinBuchmann** [comment]
I just tried to understand what was in the output. I think the problem was caused because I loaded the emacs part of slime from melpa (20190210.1101) while the swank part was loaded from quicklisp (2.22). I now load everything from quicklisp now and it seems to work. 

Does this make any sense?

**Comment by scymtym** [comment]
> Does this make any sense?

A version mismatch could certainly cause something like that. It is hard to tell without the complete output.

Since you made it work by avoiding the version mismatch and there is no clear indication what went wrong, I'm inclined to close this issue.

**Comment by MartinBuchmann** [comment]
I think there are enough real problems and I will close this issue. Thanks for your help anyway: It is good to have a forum where one can ask even a bit stupid questions ;-)

Although, I am of course embarrassed causing all the fuss with my broken config. Nevertheless, maybe this is helpful in the future for someone else.
