### ISSUE TITLE
Exception on windows SBCL 2.0.0

### ISSUE THREAD

**Issue by Ragnaroek** [sharplispers/log4cl#36]
I get this exception on windows only (context https://github.com/Ragnaroek/dandelion/issues/6). Same code works on macOS and Linux, though. SBCL versions are newer on macOS and Linux.

Maybe somebody can point me to the right direction why it is failing like this?

debugger invoked on a TYPE-ERROR in thread
#<THREAD "main thread" RUNNING {1001400523}>:
The value
#<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER>
is not of type
SB-KERNEL:CLASSOID

Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
0: [ABORT] Exit from the current thread.

(SB-KERNEL:CLASSOID-TYPEP #<SB-KERNEL:LAYOUT for LOG4CL-IMPL:DAILY-FILE-APPENDER {1002D82013}> #<SB-KERNEL:UNKNOWN-TYPE LOG4CL-IMPL:APPENDER> #<LOG4CL-IMPL:DAILY-FILE-APPENDER {1002F50E83}>)
0]

**Comment by scymtym** [comment]
I tried loading log4cl into SBCL 2.0.0 in wine and didn't immediately see any issues.

Can you provide a recipe for reproducing the issue?

**Comment by Ragnaroek** [comment]
You can reproduce it by compiling the environment in dandelion (https://github.com/Ragnaroek/dandelion/wiki/Environment-Update)

sbcl --load ./build.lisp
(build)
should produce a binary (where this is put is configurable in the build.lisp)

If you run the binary now with parameters
./env 30666 NIL DEBUG
you should see the exception.

On macOS and Linux you will get this:
<DEBUG> [08:59:58] dandelion-server server.lisp (start-eval-server) -
  Eval-Server started at 12.12.2020 08:59:58
SERVER_UP
<DEBUG> [08:59:58] dandelion-server server.lisp (start-eval-server) -
  Waiting for client connect...

**Comment by Ragnaroek** [comment]
Do you maybe have a hint on how to fix it?

**Comment by scymtym** [comment]
> Do you maybe have a hint on how to fix it?

I looked at the link you provided, but reproducing the problem that way requires too much setup. Can you try reproducing the problem in a simpler setup? Ideally, only SBCL, log4cl and a code snippet would be needed to demonstrate the problem.

**Comment by Ragnaroek** [comment]
I tried to reproduce the problem. Compiled the binary again, now it works. Maybe something in the dependencies was fixed along the way.
