### ISSUE TITLE
File appender error

### ISSUE THREAD

**Issue by K1D77A** [sharplispers/log4cl#43]
Hi,
I am not sure if this is a bug or not. 
```
ERROR - Caught SB-INT:SIMPLE-FILE-ERROR
 couldn't rename
home/manage/bluets/nasm/./logs/log.txt
to
 /home/manage/bluets/nasm/./logs/./logs/log.txt.20230204:
No such file or directory
Appender #<LOG4CL-IMPL:DAILY-FILE-APPENDER {10084486C3}> disabled
```
Thanks.

**Comment by scymtym** [comment]
Thank you for the report.  Looks like you configured the daily file appender with the filename `./logs/log.txt`. This causes a problem in `backup-log-file` which is not prepared for relative pathnames with directory component. I will push a fix.

**Comment by K1D77A** [comment]
Thanks :)
