### ISSUE TITLE
Request for registration to quicklisp

### ISSUE THREAD

**Issue by cxxxr** [sharplispers/log4cl#44]
Hi, sharplispers teams.

First of all, I would like to thank you for the maintenance of log4cl over the years.
The log4cl is working fine and I am using it conveniently.

Currently, 7max/log4cl, which is registered in quicklisp, does not seem to be maintained and does not seem to work with the newly released sbcl 2.3.3.
A fix for this is included in this repository, but it is not registered in quicklisp and cannot be used without explicitly git cloning it as a workaround.

I would therefore like to request that the log4cl registered with quicklisp be switched from 7max/log4cl to sharplispers/log4cl.
I believe that other users will benefit if this change is put in place.
Thank you in advance for your time and I hope you will accept my request.

If you have any other ideas, things I can do, etc., please let me know.

Best regards.

**Comment by dkochmanski** [comment]
I've just checked and quicklisp pulls successfully the log4cl version from sharplispers. c.f https://irclog.tymoon.eu/libera/%23clim?around=1680445090#1680445090

**Comment by cxxxr** [comment]
Sorry, I didn't check enough.
I see that this is a problem that will be resolved in the next quicklisp dist update.
Thank you very much.
