### ISSUE TITLE
 Should serialized-appender use a recursive lock?

### ISSUE THREAD

**Issue by dkochmanski** [sharplispers/log4cl#8]
https://github.com/7max/log4cl/issues/21

**Comment by dkochmanski** [comment]
Can reproduce (fixed?)

**Comment by scymtym** [comment]
> Can reproduce (fixed?)

Did you mean "Can't reproduce"? 

In any case, I can still reproduce the issue on SBCL 1.3.13 and ECL 15.3.7 with the develop branch of sharplispers/log4cl using the recipe given in 7max#21.

**Comment by dkochmanski** [comment]
OK, sorry for closing it then. Yes, that's what I meant.
